modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "ibukigourd"
version = "${version}"
displayName = "Ibuki Gourd"
authors = "forpleuvoir"
displayURL = "https://github.com/forpleuvoir/ibuki_gourd"
description = '''
呃呃呃呃呃呃呃呃
'''
#logoFile = ""

[[dependencies.ibukigourd]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ibukigourd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
