org.gradle.jvmargs = -Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon  = false

#Mod
group              = moe.forpleuvoir
mod_name           = IbukiGourd
mod_author         = forpleuvoir
mod_id             = ibukigourd
license            = MIT
description        = GUI,Config library
credits            =
version            = 0.10.3+beta



